[profile.default]
src = 'contracts'
out = 'out'
auto_detect_solc = true
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer_runs = 10
evm_version = 'shanghai'
[rpc_endpoints]
default_network = "https://ethereum-rpc.publicnode.com"
localhost = "http://127.0.0.1:8545"

gnosis = "https://rpc.gnosischain.com"
chiado = "https://rpc.chiadochain.net"
base = "https://mainnet.base.org"
baseGoerli = "https://goerli.base.org"
nordek = "https://mainnet-rpc.nordekscan.com/"
zkfair = "https://zkfair.rpc.thirdweb.com"
zkfairTestnet = "https://zkfair-testnet.rpc.thirdweb.com"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
ethereummainnet = "https://eth-mainnet.g.alchemy.com/v2/fqGfDnPHqn3CRHFFdEfXUVrPyk7DpQvT"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
